// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  envName: 'DEV',
  host: 'https://fakestoreapi.com',
  // eslint-disable-next-line max-len
  fireantToken: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkdYdExONzViZlZQakdvNERWdjV4QkRITHpnSSIsImtpZCI6IkdYdExONzViZlZQakdvNERWdjV4QkRITHpnSSJ9.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmZpcmVhbnQudm4iLCJhdWQiOiJodHRwczovL2FjY291bnRzLmZpcmVhbnQudm4vcmVzb3VyY2VzIiwiZXhwIjoxOTQxMzIzNzMxLCJuYmYiOjE2NDEzMjM3MzEsImNsaWVudF9pZCI6ImZpcmVhbnQudHJhZGVzdGF0aW9uIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsInJvbGVzIiwiZW1haWwiLCJhY2NvdW50cy1yZWFkIiwiYWNjb3VudHMtd3JpdGUiLCJvcmRlcnMtcmVhZCIsIm9yZGVycy13cml0ZSIsImNvbXBhbmllcy1yZWFkIiwiaW5kaXZpZHVhbHMtcmVhZCIsImZpbmFuY2UtcmVhZCIsInBvc3RzLXdyaXRlIiwicG9zdHMtcmVhZCIsInN5bWJvbHMtcmVhZCIsInVzZXItZGF0YS1yZWFkIiwidXNlci1kYXRhLXdyaXRlIiwidXNlcnMtcmVhZCIsInNlYXJjaCIsImFjYWRlbXktcmVhZCIsImFjYWRlbXktd3JpdGUiLCJibG9nLXJlYWQiLCJpbnZlc3RvcGVkaWEtcmVhZCJdLCJzdWIiOiJhMjcxOTgwYS02NjQ2LTQzODEtYTRjNi05NDUyMmFjMWEzYTIiLCJhdXRoX3RpbWUiOjE2NDEzMjM3MzEsImlkcCI6Ikdvb2dsZSIsIm5hbWUiOiJ2Lmh1bmdudi5ibkBnbWFpbC5jb20iLCJzZWN1cml0eV9zdGFtcCI6IjUyMWJmMTFmLWY5YWQtNDQyMi05YmViLTE3M2Y3M2Q3MmIyNCIsInByZWZlcnJlZF91c2VybmFtZSI6InYuaHVuZ252LmJuQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoidi5odW5nbnYuYm5AZ21haWwuY29tIiwiZnVsbF9uYW1lIjoiSFBHIiwiZW1haWwiOiJ2Lmh1bmdudi5ibkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6InRydWUiLCJqdGkiOiJkNjkzMjEyMmY0NzEzNzc3YzI0ZGM5ZGIyZjFmZTExMCIsImFtciI6WyJleHRlcm5hbCJdfQ.ulFAfUIz7ZRk1JCqXgrW4UPu_ONJWOPrPgbq-XWoDYEnAH0oeb3WZpXqqcUKoOqtYB_v6w88FOwyfu1EDmNKGMHZmrvYIKzzmaxKjbF92whxz12WkBg36J_fGgcVobQwSv5hrkDpYRplddOrFm_9s4Wev4VdMjoIlZ94AEFQe_1if_yn2TZrXRR5wvztKIScUHZW8INUKA6ceEaPAsGr18DbDWYw7HWwLIia_akxA-ue-7NKW2uls7UTZq5eNnc9LDq_vh7LaHc4LFTgglDOMSfjxsBObLZOvGmZuiWwwFx3F3OFcUqFRtVX8ttJOuZ9xEw51M1m_gIHG9Pudt6hWw',
  firebase: {
    apiKey: 'AIzaSyBewBx3sI8UKfBE9Y1vCdMJ85F-fqDMswQ',
    authDomain: 'angular-stock-1740f.firebaseapp.com',
    projectId: 'angular-stock-1740f',
    storageBucket: 'angular-stock-1740f.appspot.com',
    messagingSenderId: '728871156809',
    appId: '1:728871156809:web:148a31ba00dfef47125398',
    measurementId: 'G-DG38P3DP4V'
  }
};

/*
 * In development mode, to ignore zone related error stack frames such as
 * `zone.run`, `zoneDelegate.invokeTask` for easier debugging, you can
 * import the following file, but please comment it out in production mode
 * because it will have performance impact when throw error
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
