// This file can be replaced during build by using the `fileReplacements` array.
// `ng build ---prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  envName: 'DEV',
  host: 'https://fakestoreapi.com',
  firebase: {
    apiKey: 'AIzaSyBewBx3sI8UKfBE9Y1vCdMJ85F-fqDMswQ',
    authDomain: 'angular-stock-1740f.firebaseapp.com',
    projectId: 'angular-stock-1740f',
    storageBucket: 'angular-stock-1740f.appspot.com',
    messagingSenderId: '728871156809',
    appId: '1:728871156809:web:148a31ba00dfef47125398',
    measurementId: 'G-DG38P3DP4V'
  }
};

/*
 * In development mode, to ignore zone related error stack frames such as
 * `zone.run`, `zoneDelegate.invokeTask` for easier debugging, you can
 * import the following file, but please comment it out in production mode
 * because it will have performance impact when throw error
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
